---
meta:
  title: Chris D Macrae 
  titleAfter: " | Canadian Freelance Marketing Director"
  description:  
  canonical: https://chrisdmacrae.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    Dog: default-value
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/posts/:title/"
    publishDate:
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
gems:
  - octopress-minify-html
exclude:
  - package.json
  - node_modules
  - gulpfile.js
